name: dev CI

on:
  push:
  workflow_dispatch:
  # schedule:
    # - cron: '*/30 * * * *' # 每30分钟检查一次
permissions: # release需要
  contents: write   # This is required to create/push the new git tag
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get old version
        id: get_old_version
        run: |
          old_version=$(curl -s https://api.github.com/repos/Silverwolf-x/ungoogled-chromium-plus/releases/latest | jq -r .tag_name || echo "111+0.9")
          echo "OLD_VERSION=${old_version#*+}" >> $GITHUB_ENV

      - name: Get new version
        id: get_new_version
        run: |
          new_version=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r .tag_name)
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$OLD_VERSION" != "$NEW_VERSION" ] || [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            echo "Versions are different"
            echo "should_run=1" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same"
            echo "should_run=0" >> $GITHUB_OUTPUT
          fi
    outputs: 
      should_run: ${{ steps.compare_versions.outputs.should_run }}

  build:
    runs-on: ubuntu-latest
    needs: check
    # 跨jobs变量不能用env
    if: ${{ needs.check.outputs.should_run == 1 }}
    steps:
      - name: Get the latest ungoogled-chromium-windows
        run: |
          asset_url=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.assets[] | select(.name | endswith("windows_x64.zip")) | .browser_download_url')
          wget -q $asset_url -O ungoogled-chromium-windows_x64.zip

      - name: Get the latest chrome_plus
        run: |
          asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
          wget -q $asset_url -O chrome_plus-x64_arm64.7z

      - name: Unzip files
        run: |
          sudo apt-get install -y p7zip
          7z x ungoogled-chromium-windows_x64.zip 
          7z x chrome_plus-x64_arm64.7z x64  
      
      - name: Get tags and create new tag
        id: get_and_create_tag
        run: |
          UNGOOGLED_TAG=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.tag_name')
          CHROME_PLUS_TAG=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.tag_name')
          NEW_TAG="${UNGOOGLED_TAG}+${CHROME_PLUS_TAG}"
          echo "release_tag=${NEW_TAG}" >> $GITHUB_ENV

      - name: Copy files and zip
        run: |
          cp -r ungoogled-chromium_*/* x64/App/
          mv x64 ungoogled-chromium
          # 保活Data
          touch ungoogled-chromium/Data/keep
          # 删除Chromium多语言Pak
          find ungoogled-chromium/App/locales ! -name 'zh-CN.pak' ! -name 'en-US.pak' -type f -exec rm -f {} + 
          # 显示版本名称
          touch ungoogled-chromium/${{ env.release_tag }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # name: ungoogled-chromium-${{ steps.get_and_create_tag.outputs.release_tag }}
          name: ungoogled-chromium
          # path: ungoogled-chromium
          path: ungoogled-chromium

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            # name: ${{ env.RELEASE_TAG }}
            tag_name: ${{ env.release_tag }}
            # tag_name: 129.0.6668.58-1.1+1.00
            # draft: ${{ github.event_name == 'pull_request' }}
            body: |
              testtest
              test
            files: |
              ungoogled-chromium/**
            generate_release_notes: true
            fail_on_unmatched_files: true 
