name: Download and Process Latest Releases

on:
  push:
    branches:
      - main

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Download and extract the latest release of ungoogled-chromium-windows
      - name: Download latest ungoogled-chromium-windows release
        run: |
          curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest \
          | grep "*.windows_x64.zip" \
          | cut -d '"' -f 4 \
          | xargs curl -L -o ungoogled-chromium-windows.zip

      - name: Extract ungoogled-chromium-windows
        run: unzip ungoogled-chromium-windows.zip -d ungoogled-chromium-windows

      # Step 2: Download and extract the latest release of chrome_plus
      - name: Download latest chrome_plus release
        run: |
          curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest \
          | grep "*.7z" \
          | cut -d '"' -f 4 \
          | xargs curl -L -o chrome_plus.zip

      - name: Extract chrome_plus
        run: unzip chrome_plus.zip -d chrome_plus

      # Step 3: Move the ungoogled-chromium-windows content to the App folder inside chrome_plus/x64
      - name: Move ungoogled-chromium-windows to App folder
        run: |
          mkdir -p chrome_plus/x64/App
          mv ungoogled-chromium-windows/* chrome_plus/x64/App/
          
      - name: List final directory structure
        run: |
          ls -R chrome_plus/x64/App
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          path: build/release
