name: dev CI

on:
  push:
  workflow_dispatch:
  # schedule:
    # - cron: '*/30 * * * *' # 每30分钟检查一次
permissions: # release需要
  contents: write   # This is required to create/push the new git tag
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Get current version
        id: current_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ${{ github.repository }}

      - name: Get latest version
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus

      - name: Compare versions
        id: compare_versions
        run: |
          OLD_VERSION = ${{ steps.current_version.outputs.release }}
          NEW_VERSION = ${{ steps.latest_version.outputs.release }}

          if [ "$OLD_VERSION" != "$NEW_VERSION" ] || [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            echo "Versions are different"
            echo "should_run=1" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same"
            echo "should_run=0" >> $GITHUB_OUTPUT
          fi
    outputs: 
      should_run: ${{ steps.compare_versions.outputs.should_run }}


  build:
    runs-on: ubuntu-latest
    needs: check
    # 跨jobs变量不能用env
    if: ${{ needs.check.outputs.should_run == 1 }}
    steps:
      - name: Get the latest ungoogled-chromium-windows
        run: |
          asset_url=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.assets[] | select(.name | endswith("windows_x64.zip")) | .browser_download_url')
          wget -q $asset_url -O ungoogled-chromium-windows_x64.zip

      - name: Get the latest chrome_plus
        run: |
          asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
          wget -q $asset_url -O chrome_plus-x64_arm64.7z
      
      - name: Get ungoogled-chromium-windows tag
        id: ungoogled_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ungoogled-software/ungoogled-chromium-windows

      - name: Get chrome_plus tag
        id: chrome_plus_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus
      - name: Create new tag
        run: |
          echo "release_tag=${{ steps.ungoogled_tag.outputs.release }}+${{ steps.chrome_plus_tag.outputs.release }}" >> $GITHUB_ENV

      - name: Unzip files 
        run: |
          sudo apt-get install -y p7zip
          7z x ungoogled-chromium-windows_x64.zip 
          7z x chrome_plus-x64_arm64.7z x64  
      # - name: Get tags and create new tag
      #   id: get_and_create_tag
      #   run: |
      #     UNGOOGLED_TAG=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.tag_name')
      #     CHROME_PLUS_TAG=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.tag_name')
      #     NEW_TAG="${UNGOOGLED_TAG}+${CHROME_PLUS_TAG}"
      #     echo "release_tag=${NEW_TAG}" >> $GITHUB_ENV

      - name: Copy files and zip
        run: |
          cp -r ungoogled-chromium_*/* x64/App/
          mv x64 ungoogled-chromium
          # 保活Data
          touch ungoogled-chromium/Data/keep
          # 删除Chromium多语言Pak
          find ungoogled-chromium/App/locales ! -name 'zh-CN.pak' ! -name 'en-US.pak' -type f -exec rm -f {} + 
          # 显示版本名称
          touch ungoogled-chromium/${{ outputs.release_tag }}
          # 压缩为zip
          zip -r ungoogled-chromium.zip ungoogled-chromium

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ungoogled-chromium
          # path: ungoogled-chromium
          path: ungoogled-chromium.zip
    outputs: 
      release_tag: ${{ steps.ungoogled_tag.outputs.release }}+${{ steps.chrome_plus_tag.outputs.release }}


  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         # name: ungoogled-chromium-${{ steps.get_and_create_tag.outputs.release_tag }}
  #         name: ungoogled-chromium
  #         # path: ungoogled-chromium
  #         path: ungoogled-chromium/App/locales
  #   outputs: 
  #     release_tag: ${{ env.release_tag }}

  # publish-release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download package
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ungoogled-chromium
  #     - name: Display structure of downloaded files
  #       run: ls -R

      # - name: Publish release
      #   id: publish
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ needs.build.outputs.release_tag }}
      #     fail_on_unmatched_files: true
      #     files: |
      #       ungoogled-chromium.zip

    
      # - name: Download Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ungoogled-chromium
      #     path: .
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #       # name: ${{ env.RELEASE_TAG }}
      #       tag_name: ${{ env.release_tag }}
      #       # tag_name: 129.0.6668.58-1.1+1.00
      #       draft : true
      #       # draft: ${{ github.event_name == 'pull_request' }}
      #       body: |
      #         testtest
      #         test
      #       files: |
      #         ungoogled-chromium.zip
      #       generate_release_notes: true
      #       fail_on_unmatched_files: true 
