name: dev CI

on:
  push: 
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * *'  # UTC时间每天正午12点触发

permissions: # release需要
  contents: write   # This is required to create/push the new git tag
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Get current version
        id: current_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ${{ github.repository }}
        continue-on-error: true  # 允许在此步骤失败时继续执行后续步骤

      - name: Get latest chrome_plus version
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus

      - name: Compare versions
        id: compare_versions
        run: |
          OLD_VERSION=${{ steps.current_version.outputs.release }}
          OLD_VERSION=${OLD_VERSION:-0} # 如果 OLD_VERSION 是空的或未定义，则将其设置为 0
          NEW_VERSION=${{ steps.latest_version.outputs.release }}

          if [ "$OLD_VERSION" != "$NEW_VERSION" ] || [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            echo "Versions are different"
            echo "should_run=1" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same"
            echo "should_run=0" >> $GITHUB_OUTPUT
          fi
    outputs: 
      should_run: ${{ steps.compare_versions.outputs.should_run }}


  build:
    runs-on: ubuntu-latest
    needs: check
    # 跨jobs变量不能用env
    if: ${{ needs.check.outputs.should_run == 1 }}
    steps:
      - name: Get the latest ungoogled-chromium-windows
        run: |
          asset_url=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.assets[] | select(.name | endswith("windows_x64.zip")) | .browser_download_url')
          wget -q $asset_url -O ungoogled-chromium-windows_x64.zip

      - name: Get the latest chrome_plus
        run: |
          asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
          wget -q $asset_url -O chrome_plus-x64_arm64.7z
      
      - name: Get ungoogled-chromium-windows tag
        id: ungoogled_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ungoogled-software/ungoogled-chromium-windows

      - name: Get chrome_plus tag
        id: chrome_plus_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus

      - name: Unzip files 
        run: |
          sudo apt-get install -y p7zip
          7z x ungoogled-chromium-windows_x64.zip 
          7z x chrome_plus-x64_arm64.7z x64  

      - name: Copy files and zip
        run: |
          cp -r ungoogled-chromium_*/* x64/App/ # 复制
          
          mv x64 ungoogled-chromium # 重命名
          
          find ungoogled-chromium/App/locales ! -name 'zh-CN.pak' ! -name 'en-US.pak' -type f -exec rm -f {} +  # 删除Chromium多语言Pak
          
          touch ungoogled-chromium/${{ steps.ungoogled_tag.outputs.release }}+${{ steps.chrome_plus_tag.outputs.release }} # 显示版本名称
          
          zip -r ungoogled-chromium.zip ungoogled-chromium # 压缩为zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ungoogled-chromium.zip
          compression-level: 0

      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@v2 
        with:
          tag_name: ${{ steps.chrome_plus_tag.outputs.release }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            ungoogled-chromium.zip
          body: |

            ${{ steps.ungoogled_tag.outputs.release }}+${{ steps.chrome_plus_tag.outputs.release }}

            The CI follows the update period of Chrome_plus
            
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

          
