name: CI

on:
  # UTC时间每天10:00触发，北京时间每天18:00触发
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  


permissions: # release需要
  contents: write   # This is required to create/push the new git tag
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@main 
      
      - name: Get current version
        id: current_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ${{ github.repository }}
        continue-on-error: true  # 允许在此步骤失败时继续执行后续步骤

      - name: Get latest chrome_plus version
        id: chrome_plus_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus

      - name: Get ungoogled-chromium-windows version
        id: ungoogled_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ungoogled-software/ungoogled-chromium-windows

      - name: Compare versions
        id: compare_versions
        run: |
          current_ungoogled_version=$(echo ${{ steps.current_version.outputs.release }} | cut -d'+' -f1)
          current_major_version=$(echo $current_ungoogled_version | cut -d'.' -f1)
          # current_ungoogled_version=129.0.6668.58

          current_chrome_plus_version=$(echo ${{ steps.current_version.outputs.release }} | cut -d'+' -f2)
          # current_chrome_plus_version=1.10.0

          latest_ungoogled_version=$(echo ${{ steps.ungoogled_tag.outputs.release }}| cut -d'-' -f1)
          latest_major_version=$(echo $latest_ungoogled_version | cut -d'.' -f1)
          latest_chrome_plus_version=${{ steps.chrome_plus_tag.outputs.release }}
          
          echo "current_ungoogled_version=$current_ungoogled_version"
          echo "current_major_version=$current_major_version"
          echo "current_chrome_plus_version=$current_chrome_plus_version"
          echo "latest_ungoogled_version=$latest_ungoogled_version"
          echo "latest_major_version=$latest_major_version" 
          echo "latest_chrome_plus_version=$latest_chrome_plus_version" 

          if [ "${current_chrome_plus_version}" != "${latest_chrome_plus_version}" ] || [ "${current_major_version}" != "${latest_major_version}" ]; then
            echo "build release"
            echo "should_run=release" >> $GITHUB_OUTPUT
          elif [ "${current_ungoogled_version}" != "${latest_ungoogled_version}" ]; then
            echo "build prerelease"
            echo "should_run=prerelease" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same"
            echo "should_run=" >> $GITHUB_OUTPUT
          fi

    outputs: 
      should_run: ${{ steps.compare_versions.outputs.should_run }}
      chrome_plus_tag: ${{ steps.chrome_plus_tag.outputs.release }}
      ungoogled_tag: ${{ steps.ungoogled_tag.outputs.release }}


  release:
    runs-on: ubuntu-latest
    needs: check
    # 跨jobs变量不能用env
    if: ${{ needs.check.outputs.should_run }}
    steps:
      - name: echo all needs.check.outputs
        run: |
          echo "Current job should run: ${{ needs.check.outputs.should_run }}"
          echo "Chrome Plus tag: ${{ needs.check.outputs.chrome_plus_tag }}"
          echo "Ungoogled tag: ${{ needs.check.outputs.ungoogled_tag }}"

      - name: get latest release download of ungoogled-chromium-windows
        uses: robinraju/release-downloader@main
        with:
          repository: ungoogled-software/ungoogled-chromium-windows
          tag: ${{ needs.check.outputs.ungoogled_tag }}
          fileName: '*windows_x64.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: get latest release download of chrome_plus
        uses: robinraju/release-downloader@main
        with:
          repository: Bush2021/chrome_plus
          tag: ${{ needs.check.outputs.chrome_plus_tag }}
          fileName: '*x86_x64_arm64.7z'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in workspace
        run: |
          echo "当前目录内容如下："
          ls -lh


      # - name: get latest release download of chrome_plus and prerelease
      #   run: |
      #     asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
      #     wget -q $asset_url -O chrome_plus-x64_arm64.7z

      # - name: Get the latest ungoogled-chromium-windows and chrome_plus
      #   run: |
      #     asset_url=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.assets[] | select(.name | endswith("windows_x64.zip")) | .browser_download_url')
      #     wget -q $asset_url -O ungoogled-chromium-windows_x64.zip

      #     asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
      #     wget -q $asset_url -O chrome_plus-x64_arm64.7z

      #     echo "ungoogled_tag=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.name'| cut -d'-' -f1)" >> $GITHUB_ENV

      #     echo "plus_tag=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.name')" >> $GITHUB_ENV

      - name: Unzip need files 
        run: |
          sudo apt-get install -y p7zip
          7z x ungoogled-chromium-windows_x64.zip 
          7z x chrome_plus-x64_arm64.7z x64  

      - name: Copy files and zip
        run: |
          cp -r ungoogled-chromium_*/* x64/App/ # 复制
          
          mv x64 ungoogled-chromium # 重命名
          
          find ungoogled-chromium/App/locales ! -name 'zh-CN.pak' ! -name 'en-US.pak' -type f -exec rm -f {} +  # 删除Chromium多语言Pak
          
          touch ungoogled-chromium/${{ env.ungoogled_tag }}+${{ env.plus_tag }} # 显示版本名称
          
          zip -r ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip ungoogled-chromium # 压缩为zip

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          path: ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          compression-level: 0

      - name: Publish release
        if: ${{ needs.check.outputs.should_run == 'release' }}
        uses: softprops/action-gh-release@master
        with:
          name: ${{ env.ungoogled_tag }}
          tag_name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          body: |

            ${{ env.ungoogled_tag }}+${{ env.plus_tag }}

            **The release follows the update f Chrome_plus and major version update of ungoogled-chromium-windows**
            
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

      - name: Publish prerelease
        if: ${{ needs.check.outputs.should_run == 'prerelease' }}
        uses: softprops/action-gh-release@master
        with:
          prerelease: true
          name: ${{ env.ungoogled_tag }}
          tag_name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          body: |

            ${{ env.ungoogled_tag }}+${{ env.plus_tag }}

            **The prerelease follows the update only of ungoogled-chromium-windows**
            
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

          
