name: Sync and Publish Chromium Releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push,release]

jobs:
  sync_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Get the latest ungoogled-chromium-windows windows_x64.zip
        run: |
          asset_url=$(curl -s https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest | jq -r '.assets[] | select(.name | endswith("windows_x64.zip")) | .browser_download_url')
          wget -q $asset_url -O ungoogled-chromium-windows_x64.zip

      - name: Get the latest chrome_plus x64_arm64.7z
        run: |
          asset_url=$(curl -s https://api.github.com/repos/Bush2021/chrome_plus/releases/latest | jq -r '.assets[] | select(.name | endswith("x86_x64_arm64.7z")) | .browser_download_url')
          wget -q $asset_url -O chrome_plus-x64_arm64.7z

      - name: Unzip ungoogled-chromium-windows windows_x64.zip
        run: |
          unzip -o ungoogled-chromium-windows_x64.zip -d ungoogled-chromium/

      - name: Unzip chrome_plus x64_arm64.7z
        run: |
          sudo apt-get install -y p7zip-full
          7z x chrome_plus-x64_arm64.7z mv chrome_plus
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
