name: CI

on:
  # UTC时间每天10:00触发，北京时间每天18:00触发
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  


permissions: # release需要
  contents: write   # This is required to create/push the new git tag
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@main 
      
      - name: Get current version
        id: current_version
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ${{ github.repository }}
        continue-on-error: true  # 允许在此步骤失败时继续执行后续步骤

      - name: Get latest chrome_plus version
        id: chrome_plus_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: Bush2021/chrome_plus
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get ungoogled-chromium-windows version
        id: ungoogled_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          repository: ungoogled-software/ungoogled-chromium-windows
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compare versions
        id: compare_versions
        shell: bash
        run: |
          cur_ver="${{ steps.current_version.outputs.release }}"
          latest_ungoogled="${{ steps.ungoogled_tag.outputs.release }}"
          latest_plus="${{ steps.chrome_plus_tag.outputs.release }}"

          cur_ungoogled="${cur_ver%%+*}"
          cur_major="${cur_ungoogled%%.*}"
          cur_plus="${cur_ver#*+}"

          latest_ungoogled_base="${latest_ungoogled%%-*}"
          latest_major="${latest_ungoogled_base%%.*}"

          echo "cur_ungoogled=$cur_ungoogled"
          echo "cur_major=$cur_major"
          echo "cur_plus=$cur_plus"
          echo "latest_ungoogled=$latest_ungoogled_base"
          echo "latest_major=$latest_major"
          echo "latest_plus=$latest_plus"

          if [[ "$cur_plus" != "$latest_plus" || "$cur_major" != "$latest_major" ]]; then
            echo "should_run=release" >> "$GITHUB_OUTPUT"
          elif [[ "$cur_ungoogled" != "$latest_ungoogled_base" ]]; then
            echo "should_run=prerelease" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=" >> "$GITHUB_OUTPUT"
          fi

    outputs: 
      should_run: ${{ steps.compare_versions.outputs.should_run }}
      chrome_plus_tag: ${{ steps.chrome_plus_tag.outputs.release }}
      ungoogled_tag: ${{ steps.ungoogled_tag.outputs.release }}


  release:
    runs-on: ubuntu-latest
    needs: check
    # 跨jobs变量不能用env
    if: ${{ needs.check.outputs.should_run || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: get latest release download of ungoogled-chromium-windows
        uses: robinraju/release-downloader@main
        with:
          repository: ungoogled-software/ungoogled-chromium-windows
          tag: ${{ needs.check.outputs.ungoogled_tag }}
          fileName: '*windows_x64.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: get latest release download of chrome_plus
        uses: robinraju/release-downloader@main
        with:
          repository: Bush2021/chrome_plus
          tag: ${{ needs.check.outputs.chrome_plus_tag }}
          fileName: '*x86_x64_arm64.7z'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in workspace
        run: |
          echo "当前目录内容如下："
          ls -lh

      - name: Unzip need files 
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          7z x ungoogled-chromium_*.zip
          7z x Chrome++*.7z x64
      - name: Set environment variables
        run: |
          raw_tag="${{ needs.check.outputs.ungoogled_tag }}"
          clean_tag="${raw_tag%%-*}"
          echo "ungoogled_tag=$clean_tag" >> $GITHUB_ENV
          echo "plus_tag=${{ needs.check.outputs.chrome_plus_tag }}" >> $GITHUB_ENV
      - name: Copy files and zip
        run: |
          cp -r ungoogled-chromium_*/* x64/App/ # 复制
          
          mv x64 ungoogled-chromium # 重命名
          
          find ungoogled-chromium/App/locales ! -name 'zh-CN.pak' ! -name 'en-US.pak' -type f -exec rm -f {} +  # 删除Chromium多语言Pak
          
          touch ungoogled-chromium/${{ env.ungoogled_tag }}+${{ env.plus_tag }} # 显示版本名称
          
          zip -r ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip ungoogled-chromium # 压缩为zip

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          path: ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          compression-level: 0

      - name: Publish release
        if: ${{ needs.check.outputs.should_run == 'release' && github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@master
        with:
          name: ${{ env.ungoogled_tag }}
          tag_name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          fail_on_unmatched_files: true
          files: |
            ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          body: |

            ${{ env.ungoogled_tag }}+${{ env.plus_tag }}

            **The release follows the update of Chrome_plus and major version update of ungoogled-chromium-windows**
            
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

      - name: Publish prerelease
        if: ${{ needs.check.outputs.should_run == 'prerelease' && github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@master
        with:
          prerelease: true
          name: ${{ env.ungoogled_tag }}
          tag_name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          fail_on_unmatched_files: true
          files: |
            ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          body: |

            ${{ env.ungoogled_tag }}+${{ env.plus_tag }}

            **The prerelease follows the update only of ungoogled-chromium-windows**
            
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

      - name: Publish draft (manual trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@master
        with:
          draft: true
          name: ${{ env.ungoogled_tag }}
          tag_name: ${{ env.ungoogled_tag }}+${{ env.plus_tag }}
          fail_on_unmatched_files: true
          files: ungoogled-chromium_${{ env.ungoogled_tag }}_windows_x64.zip
          body: |
            ${{ env.ungoogled_tag }}+${{ env.plus_tag }}

            Manually triggered draft release.

            Sources:
            - [Chrome_plus](https://github.com/Bush2021/chrome_plus)
            - [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

